[package]
name = "pairing"

# Remember to change version string in README.md.
version = "0.14.1"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/ebfull/pairing"
repository = "https://github.com/ebfull/pairing"

[dependencies]
blake2-rfc = "0.2.18"
rand = "0.4"
byteorder = "1"
clippy = { version = "0.0.190", optional = true }

[features]
unstable-features = ["expose-arith"]
expose-arith = []
u128-support = []
default = []

[lib]
name = "pairing"
crate-type = ["staticlib"]
